export enum Paths {
  HOME = 'home',
  PROFILE = 'profile',
  RIDDLE = 'riddle',
  TASKS = 'tasks',
  NEWS = 'news',
  EVENTS = 'event',
  IMPRESSUM = 'impressum',
  TOKEN = 'token',
  TOKEN_SCANNED = 'token-scanned',
  COMMUNITIES = 'communities',
  ERROR = 'error',
  EXTRA_PAGE = 'page',
  FORM = 'form',
  LEADER_BOARD = 'leaderboard',
  RACE = 'race',
  TEAMS = 'teams',
  CREATE_TEAM = 'create-team',
  MY_TEAM = 'my-team',
  TEAM_ADMIN = 'team-admin'
}

export enum AbsolutePaths {
  HOME = '/home',
  PROFILE = '/profile',
  RIDDLE = '/riddle',
  TASKS = '/tasks',
  NEWS = '/news',
  EVENTS = '/event',
  IMPRESSUM = '/impressum',
  TOKEN = '/token',
  TOKEN_SCANNED = 'token-scanned',
  COMMUNITIES = '/communities',
  ERROR = '/error',
  EXTRA_PAGE = '/page',
  FORM = '/form',
  RACE = '/race',
  TEAMS = '/teams',
  CREATE_TEAM = '/create-team',
  MY_TEAM = '/my-team',
  TEAM_ADMIN = '/team-admin'
}
