export enum Paths {
  HOME = 'home',
  PROFILE = 'profile',
  RIDDLE = 'riddle',
  TASKS = 'tasks',
  NEWS = 'news',
  EVENTS = 'event',
  IMPRESSUM = 'impressum',
  TOKEN = 'token',
  TOKEN_SCANNED = 'token-scanned',
  COMMUNITY = 'community',
  ORGANIZATION = 'orgaization',
  ERROR = 'error',
  EXTRA_PAGE = 'page',
  FORM = 'form',
  LEADER_BOARD = 'leaderboard',
  RACE = 'race',
  QR_FIGHT = 'qr-fight',
  TEAMS = 'teams',
  CREATE_TEAM = 'create-team',
  MY_TEAM = 'my-team',
  TEAM_ADMIN = 'team-admin'
}

export enum AbsolutePaths {
  HOME = '/home',
  PROFILE = '/profile',
  RIDDLE = '/riddle',
  TASKS = '/tasks',
  NEWS = '/news',
  EVENTS = '/event',
  IMPRESSUM = '/impressum',
  TOKEN = '/token',
  TOKEN_SCANNED = 'token-scanned',
  COMMUNITY = '/community',
  ORGANIZATION = '/organization',
  ERROR = '/error',
  EXTRA_PAGE = '/page',
  FORM = '/form',
  RACE = '/race',
  TEAMS = '/teams',
  CREATE_TEAM = '/create-team',
  MY_TEAM = '/my-team',
  TEAM_ADMIN = '/team-admin',
  QR_FIGHT = '/qr-fight',
  LEADER_BOARD = '/leaderboard'
}

export enum ApiPaths {
  CONFIG = '/api/app',
  EVENTS = '/api/events',
  FORM = '/api/form',
  PAGE = '/api/page',
  NEWS = '/api/news',
  RACE = '/api/race',
  RIDDLE = '/api/riddle',
  TASK = '/api/task',
  TASK_SUBMIT = '/api/task/submit',
  REFRESH = '/api/control/refresh',
  WARNING = '/api/warning',
  TASK_CATEGORY = '/api/task/category',
  PROFILE = '/api/profile',
  LEVELS = '/api/LEVELS',
  LOCATION = '/api/track-my-group',
  TOKENS = '/api/tokens',
  CHANGE_ALIAS = '/api/profile/change-alias',
  COMMUNITY = '/api//community',
  ORGANIZATION = '/api/organization'
}
