{{ if and (not .Values.s3.useS3) .Values.driveBackup.filesystem.enabled }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-filesystem-backup-secrets
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
data:
  GOOGLE_SERVICE_ACCOUNT_KEY: {{ .Values.driveBackup.googleServiceAccount | b64enc }}
  DRIVE_PARENT_ID: {{ .Values.driveBackup.driveParentId | b64enc }}
  DRIVE_ID: {{ .Values.driveBackup.driveId | b64enc }}
type: Opaque
{{ end }}
