{{ if not .Values.s3.useS3 }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-pv
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.resources.requests.storage }}
{{ if  .Values.resources.storageClassName  }}
  storageClassName: {{ .Values.resources.storageClassName }}
{{ end }}
{{ if  .Values.resources.volumeMode  }}
  volumeMode: {{ .Values.resources.volumeMode }}
{{ end }}
{{ end }}
