kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
    app.kubernetes.io/name: {{ .Release.Name }}
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http-{{ .Release.Name }}
  selector:
    app: {{ .Release.Name }}
    app.kubernetes.io/name: {{ .Release.Name }}
  type: {{ .Values.service.type }}
  sessionAffinity: None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster
