kind: Secret
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
data:
  JWT_SECRET: {{ .Values.secret.jwtSecret | b64enc }}
  PROFILE_SALT: {{ .Values.secret.profileSalt | b64enc }}
  AUTHSCH_CLIENT_ID: {{ .Values.secret.authschClientId | b64enc }}
  AUTHSCH_CLIENT_KEY: {{ .Values.secret.authschClientKey | b64enc }}
  BMEJEGY_USERNAME: {{ .Values.secret.bmejegyUsername | b64enc }}
  BMEJEGY_PASSWORD: {{ .Values.secret.bmejegyPassword | b64enc }}
  GOOGLE_CLIENT_ID: {{ .Values.secret.googleClientId | b64enc }}
  GOOGLE_CLIENT_KEY: {{ .Values.secret.googleClientKey | b64enc }}
  FIREBASE_SERVICE_ACCOUNT_KEY: {{ .Values.secret.firebaseServiceAccountKey | b64enc }}
type: Opaque
