kind: Secret
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-postgres-backup-secrets
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
data:
  GOOGLE_SERVICE_ACCOUNT_KEY: {{ .Values.postgres.driveBackup.googleServiceAccount | b64enc }}
  DRIVE_PARENT_ID: {{ .Values.postgres.driveBackup.driveParentId | b64enc }}
  DRIVE_ID: {{ .Values.postgres.driveBackup.driveId | b64enc }}
  PGPASSWORD: {{ .Values.postgres.global.postgresql.auth.password | b64enc }}
  PGUSER: {{ .Values.postgres.global.postgresql.auth.username | b64enc }}
type: Opaque
