{{ if .Values.ingress.enabled }}
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
  {{- with .Values.ingress.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  tls:
    - hosts:
        - {{ .Values.apiHost }}
      secretName: {{ .Release.Name }}-cert
  rules:
    - host: {{ .Values.apiHost }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}
                port:
                  number: 80
          {{ if .Values.blockActuatorEndpoints }}
          - path: /actuator/
            pathType: Prefix
            backend:
              service:
                name: default-backend
                port:
                  number: 80
          {{ end }}
{{ end }}
