kind: Secret
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
data:
  JWT_SECRET: {{ .Values.secret.jwtSecret | b64enc }}
  PROFILE_SALT: {{ .Values.secret.profileSalt | b64enc }}
  AUTHSCH_CLIENT_ID: {{ .Values.secret.authschClientId | b64enc }}
  AUTHSCH_CLIENT_KEY: {{ .Values.secret.authschClientKey | b64enc }}
  BMEJEGY_USERNAME: {{ .Values.secret.bmejegyUsername | b64enc }}
  BMEJEGY_PASSWORD: {{ .Values.secret.bmejegyPassword | b64enc }}
  GOOGLE_CLIENT_ID: {{ .Values.secret.googleClientId | b64enc }}
  GOOGLE_CLIENT_KEY: {{ .Values.secret.googleClientKey | b64enc }}
  FIREBASE_SERVICE_ACCOUNT_KEY: {{ .Values.secret.firebaseServiceAccountKey | b64enc }}
  {{ if .Values.postgres.enabled }}
  POSTGRES_USER: {{ .Values.postgres.global.postgresql.auth.username | b64enc }}
  POSTGRES_PW: {{ .Values.postgres.global.postgresql.auth.password | b64enc }}
  POSTGRES_DB: {{ .Values.postgres.global.postgresql.auth.database | b64enc }}
  {{ end }}
  {{ if .Values.s3.enabled }}
  S3_ACCESS_KEY: {{ .Values.s3.accessKey | b64enc }}
  S3_SECRET_KEY: {{ .Values.s3.secretKey | b64enc }}
  {{ end }}
type: Opaque
