server {
  listen 80;
  root /usr/share/nginx/html;

  location = /index.html {
    add_header Cache-Control "no-cache";
  }

  location /assets/ {
    add_header Cache-Control "public, max-age=31536000, immutable";
  }

  location / {
    index index.html index.htm;
    try_files $uri $uri/ /index.html =404;
    add_header Cache-Control "no-cache";
  }
}
