FROM gradle:jdk21 as build
COPY --chown=gradle:gradle . /home/gradle/src
WORKDIR /home/gradle/src
RUN gradle clean assemble bootJar

FROM eclipse-temurin:21-jre-jammy
MAINTAINER kir-dev@sch.bme.hu
COPY --from=build /home/gradle/src/build/libs/cmsch.jar /opt/cmsch/
WORKDIR /opt/cmsch
ENTRYPOINT ["java", "-Dspring.profiles.include=docker", "-XX:+UnlockExperimentalVMOptions", "-XX:+UseContainerSupport", "-XX:+UseSerialGC", "-XX:MaxRAMPercentage=90", "-jar", "/opt/cmsch/cmsch.jar"]
EXPOSE 80
