FROM gradle:jdk23 as build
COPY --chown=gradle:gradle . /home/gradle/src
WORKDIR /home/gradle/src
RUN gradle clean assemble bootJar

FROM eclipse-temurin:23-jre-alpine
MAINTAINER kir-dev@sch.bme.hu
COPY --from=build /home/gradle/src/build/libs/cmsch.jar /opt/cmsch/
WORKDIR /opt/cmsch

RUN java -Djarmode=tools -jar cmsch.jar extract --destination application
RUN rm cmsch.jar

WORKDIR /opt/cmsch/application
RUN java "-Dspring.profiles.include=prewarm" "-XX:ArchiveClassesAtExit=application.jsa" "-XX:+UnlockExperimentalVMOptions" "-XX:+UseContainerSupport" "-XX:+UseSerialGC" "-XX:MaxRAMPercentage=90" "-Dspring.context.exit=onRefresh" -jar cmsch.jar

ENTRYPOINT ["java", "-Dspring.profiles.include=docker", "-XX:SharedArchiveFile=application.jsa", "-XX:+UnlockExperimentalVMOptions", "-XX:+UseContainerSupport", "-XX:+UseSerialGC", "-XX:MaxRAMPercentage=90", "-jar", "/opt/cmsch/application/cmsch.jar"]
EXPOSE 80
