kind: Secret
apiVersion: v1
metadata:
  name: golyakorte-staging-secrets
  namespace: org-golyakorte-staging
data:
  AuthSCH_ID: TODO-base64-20chars
  AuthSCH_KEY: >-
    TODO-base64-80chars
  MySQL_USER: TODO-base64-user
  MySQL_PASSWORD: TODO-base64-password
type: Opaque
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: golyakorte-example
  namespace: org-golyakorte-staging
  managedFields:
    - manager: kubectl-client-side-apply
      operation: Update
      apiVersion: apps/v1
      time: '2022-01-20T08:10:35Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:spec:
          f:progressDeadlineSeconds: {}
          f:replicas: {}
          f:revisionHistoryLimit: {}
          f:selector: {}
          f:strategy:
            f:rollingUpdate:
              .: {}
              f:maxSurge: {}
              f:maxUnavailable: {}
            f:type: {}
          f:template:
            f:metadata:
              f:labels:
                .: {}
                f:app: {}
            f:spec:
              f:containers:
                k:{"name":"golyakorte-example"}:
                  .: {}
                  f:env: {}
                  f:imagePullPolicy: {}
                  f:name: {}
                  f:ports:
                    .: {}
                    k:{"containerPort":80,"protocol":"TCP"}:
                      .: {}
                      f:containerPort: {}
                      f:protocol: {}
                  f:resources:
                    .: {}
                    f:limits: {}
                  f:terminationMessagePath: {}
                  f:terminationMessagePolicy: {}
                  f:volumeMounts:
                    .: {}
                    k:{"mountPath":"/pv"}:
                      .: {}
                      f:mountPath: {}
                      f:name: {}
              f:dnsPolicy: {}
              f:restartPolicy: {}
              f:schedulerName: {}
              f:securityContext: {}
              f:terminationGracePeriodSeconds: {}
              f:volumes:
                .: {}
                k:{"name":"golyakorte-example"}:
                  .: {}
                  f:name: {}
                  f:persistentVolumeClaim:
                    .: {}
                    f:claimName: {}
    - manager: dashboard
      operation: Update
      apiVersion: apps/v1
      time: '2022-01-20T14:31:09Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          f:template:
            f:spec:
              f:containers:
                k:{"name":"golyakorte-example"}:
                  f:env:
                    k:{"name":"AUTHSCH_CLIENT_ID"}:
                      .: {}
                      f:name: {}
                      f:valueFrom:
                        .: {}
                        f:secretKeyRef: {}
                    k:{"name":"AUTHSCH_CLIENT_KEY"}:
                      .: {}
                      f:name: {}
                      f:valueFrom:
                        .: {}
                        f:secretKeyRef: {}
                    k:{"name":"PORT"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"PROFILE_SALT"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"SYSADMINS"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"WEBSITE_URL"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                  f:image: {}
                  f:resources:
                    f:limits:
                      f:memory: {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: apps/v1
      time: '2022-01-20T14:49:53Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:deployment.kubernetes.io/revision: {}
        f:status:
          f:availableReplicas: {}
          f:conditions:
            .: {}
            k:{"type":"Available"}:
              .: {}
              f:lastTransitionTime: {}
              f:lastUpdateTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
            k:{"type":"Progressing"}:
              .: {}
              f:lastTransitionTime: {}
              f:lastUpdateTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
          f:observedGeneration: {}
          f:readyReplicas: {}
          f:replicas: {}
          f:updatedReplicas: {}
      subresource: status
spec:
  replicas: 1
  selector:
    matchLabels:
      app: golyakorte-example
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: golyakorte-example
    spec:
      volumes:
        - name: golyakorte-example
          persistentVolumeClaim:
            claimName: golyakorte-example
      containers:
        - name: golyakorte-example
          image: harbor.sch.bme.hu/org-golyakorte/cmsch:rc
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: SPRING_PROFILES
              value: 'staging,golyakorte2022,test'
            - name: PORT
              value: '80'
            - name: REQUEST_FOR_NEPTUN_DEFAULT
              value: 'true'
            - name: REQUEST_FOR_EMAIL_DEFAULT
              value: 'false'
            - name: WEBSITE_URL
              value: https://staging.golyakorte.sch.bme.hu/
            - name: SYSADMINS
              value: >-
                6af3c8b0-592c-6864-8dd9-5f354edfc0be,814e5203-9fd0-8a91-c952-7d05979b4184,0e81d7b8-7758-724c-8c50-744e4a2aefb9,ceceec21-3b1d-7917-f2c4-d1bf1e1f44ad
            - name: PROFILE_SALT
              value: example_salt
            - name: AUTHSCH_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: golyakorte-staging-secrets
                  key: AuthSCH_ID
            - name: AUTHSCH_CLIENT_KEY
              valueFrom:
                secretKeyRef:
                  name: golyakorte-staging-secrets
                  key: AuthSCH_KEY
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: golyakorte-staging-secrets
                  key: MySQL_USER
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: golyakorte-staging-secrets
                  key: MySQL_PASSWORD
            - name: DATABASE_URL
              value: 'jdbc:mysql://10.0.208.72:3306/golyakorte-staging?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=yes&characterEncoding=utf8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC'
          resources:
            limits:
              memory: 512Mi
          volumeMounts:
            - name: golyakorte-example
              mountPath: /pv
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
