version: '3.7'

services:
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 3000:80

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile-build
    environment:
      PORT: 8080
      FRONTEND_URL: http://localhost:3000
      BACKEND_URL: http://localhost:8080/
      CMSCH_SPRING_PROFILES: prod,keycloak
      JWT_SECRET: todo_jwt_secret
      PROFILE_SALT: todo_profile_salt
      KEYCLOAK_BASEURL: http://localhost:8081/
      KEYCLOAK_BASEURL_FROM_BACKEND: http://keycloak:8080/
      AUTHSCH_CLIENT_ID: 0
      AUTHSCH_CLIENT_KEY: 0
      KEYCLOAK_CLIENT_ID: cmsch
      KEYCLOAK_CLIENT_SECRET: 1iPL7aTT20lSfza7DK8en7aZDiF01A0i
      KEYCLOAK_ISSUER: http://localhost:8081/realms/snyt
      KEYCLOAK_REALM: snyt
    ports:
      - 8080:8080
