version: '3.7'

services:
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 3000:80

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile-build
    env_file:
      - .env
    ports:
      - 8080:8080
    volumes:
      - cmsch:/pv
volumes:
  cmsch: