version: '3.7'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:21.1.2
    env_file:
      - .env
    ports:
      - 8081:8080
    depends_on:
      - postgres
    command:
      - start-dev

  postgres:
    image: postgres
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data: