name: Build CI with Gradle

on:
  push:
    branches: 
      - master
    paths:
      - 'backend/**'
  pull_request:
    branches: 
      - master
    paths:
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
    - name: Check out Git repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: temurin

    - name: Gradle CI
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build
        build-root-directory: backend
